# Generated by Django 5.1b1 on 2024-09-14 21:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)])),
                ('english_word', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)])),
                ('polish_word', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)])),
                ('english_sentence', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(10)])),
                ('polish_sentence', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(10)])),
                ('level', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='wordmaster.vocabulary')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_date', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('sentences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='wordmaster.vocabulary')),
            ],
        ),
    ]
